# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - qRate-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your function app project
  NODE_VERSION: '22.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install and build project
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          # Skipping tests since none are defined
          popd

      - name: Zip artifact for deployment
        run: |
          cd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d deploy-package

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'qRate-backend'
          slot-name: 'Production'
          package: deploy-package
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8AA68F4B098945DEAF57A8E5A6A77941 }}
